version: '3.6'
services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - '8000:8000'
    environment:
      - SPLUNK_PASSWORD=123splunklabA
      - SPLUNK_START_ARGS=--accept-license